name: SQLFactory

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      HTTP_ADDR: ":8080"
      MYSQL_ADDR: "mysql:3306"
      REDIS_ADDR: "redis:6379"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  mysql:
    container_name: mysql_SQLFactory
    image: mysql:8
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_DATABASE: $MYSQL_SCHEMA
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 3

  migrations:
    container_name: migrations_SQLFactory
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile-migration
    environment:
      GOOSE_DRIVER: "mysql"
      GOOSE_DBSTRING: "root:$MYSQL_ROOT_PASSWORD@tcp(mysql)/$MYSQL_SCHEMA?parseTime=true"
    depends_on:
      mysql:
        condition: service_healthy

  redis:
    image: redis:alpine
    container_name: redis_cache_SQLFactory
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    command: ["redis-server", "--requirepass", "pass"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "pass", "ping"]
      timeout: 5s
      interval: 5s
      retries: 3

  test_db:
    image: postgres:18.0
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test
    volumes:
      - ./db/testdata/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/testdata/orders.csv:/testdata/orders.csv
    ports:
      - "5432:5432"